development:
  adapter: postgresql
  encoding: utf8
  database: stmdb
  pool: 5
  username: shumgena
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: stmdb_test
  pool: 5
  username: shumgena
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: stmdb_prod
  pool: 5
  username: shumgena
  password:
  host: localhost