development:
  adapter: postgresql
  encoding: utf8
  database: stmdb
  pool: 5
  username: vagrant
  password: 1
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: stmdb_test
  pool: 5
  username: postgres
  password: 1
  host: localhost
